# Add configuration values here, as shown below.
HELLO_WORLD_DATABASE_PASSWORD: ENV['DATABASE_PASSWORD']
HELLO_WORLD_DATABASE_HOST: ENV['DATABASE_HOST']
HELLO_WORLD_DATABASE_PORT: ENV['DATABASE_PORT']
SECRET_KEY_BASE: ENV['SECRET_KEY_BASE']
